### ISSUE TITLE
Make a KanBan Board for the Hotel Booking Capstone Project

### ISSUE THREAD

**Issue by paulshaun-kdtk** [paulshaun-kdtk/Hotel-Booking#14]
# We are a team of 5 members
- Muhammand Zunair Khan [@zunairkhan811 ]
- Assem Zhorabay [@zhorabay ]
- Anthony Obi [@Megagig]
- Mumbere Herbet [@mumbereh]
- Shaun Paul [@paulshaun-kdtk]

## Changes
- link for our GitHub project: https://github.com/users/paulshaun-kdtk/projects/3
- we assigned all tasks equally among all team member
- screenshot of kanban board: 
![image](https://github.com/paulshaun-kdtk/Hotel-Booking1/assets/123934813/84154ac3-591b-444f-9f9d-23670383c6e5)

**Comment by Meltrust** [comment]
Hi,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not contain a screenshot of the kanban board.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Meltrust** [comment]
## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have descriptions, assignees, and pointings according to spec✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
